### ISSUE TITLE
Angular2 folder structure support

### ISSUE THREAD

**Issue by MrBokeh** [rossmartin/cordova-uglify#15]
Are you planning to add angular 2 with es6 support?

**Comment by rossmartin** [comment]
Yeah I'm pretty sure I just need to update the default directory that is used to recursively search for `.js` and `.css` files.  I don't think I'll need to update `ng-annotate` and `UglifyJS`.

**Comment by MrBokeh** [comment]
Actually I should rephrase it, if you use ionic 2 with Angular 2. It will transpire all es6 files to one big es5 .js file regardless you use .js or.ts for your es6 script. And all the .sass files into one big .css file. All the .html files can be remain or in .js depends on if you use that htm like to js minifier or not.

**Comment by rossmartin** [comment]
I'm starting to learn Ionic 2, I plan on supporting it soon.  I think `cordova-uglify` will have to be placed in the `ionic.config.js` file.

**Comment by apparition47** [comment]
I'm using `cordova-uglify` with a webpack Angular2 project and it works fine except when [UglifyJS2 mangles the component names in my project.](https://github.com/mishoo/UglifyJS2/issues/999). Using the following in my `uglify-config.json` allows my uglified code to run:

```
    "uglifyJsOptions": {
        "mangle" :false,
    },
```

Just thought I'd put this out there for people having the same issue.

**Comment by rossmartin** [comment]
@apparition47 Thanks for the info I'll give it a try soon.

**Comment by apparition47** [comment]
Yes! This setting works with the default Ionic 2 seed.

**Comment by rossmartin** [comment]
Looks like all that is needed to get `cordova-uglify` working with Ionic 2 is to update the `uglify-config.json`.

- Add `"build"` to the "foldersToProcess" array property in `uglify-config.json`

```
...
    "foldersToProcess": [
        "build"
    ],
...
```
- Add `"mangle": false` to the `"uglifyJsOptions"` in the `uglify-config.json` -
```
...
    "uglifyJsOptions": {
        "compress": {
            "drop_console": true
        },
        "fromString": true,
        "mangle" :false
    },
...
```

I'm going to update the readme and add this info.  Thanks @apparition47  @MrBokeh

**Comment by apparition47** [comment]
@rossmartin I noticed you updated your README, but `"mangle": true` there, which doesn't work for Angular 2 at the moment. Is that a mistake?

**Comment by MrBokeh** [comment]
@apparition47 here is my settings which seems works well
```
"alwaysRun": false,
    "recursiveFolderSearch": true,
    "foldersToProcess": [
        "js",
        "css",
        "img",
        "build"
    ],
    "uglifyJsOptions": {
        "compress": {
            "drop_console": true
        },
        "fromString": true,
        "mangle" :false
    },
```

**Comment by rossmartin** [comment]
@apparition47 Thanks I have a [section that describes how to use it with Ionic 2 ](https://github.com/rossmartin/cordova-uglify#using-cordova-uglify-with-ionic-2).  Also in the [configuration](https://github.com/rossmartin/cordova-uglify#configuration) I note to set `mangle` to `false` to work with Ionic 2.

Thanks for the help.
