### ISSUE TITLE
Error with dependencies

### ISSUE THREAD

**Issue by tetsuo2501** [rossmartin/cordova-uglify#16]
I tried to install cordova-uglify, but I had an error:
├── UNMET PEER DEPENDENCY clean-css@3.4.8
├── UNMET PEER DEPENDENCY imagemin@4.0.0
├── UNMET PEER DEPENDENCY ng-annotate@1.0.2
└── UNMET PEER DEPENDENCY uglify-js@2.6.1

So I installed depencecies (it works) but these unmet dependencies remains...

**Comment by rossmartin** [comment]
Thanks I believe this occurs with npm >= 3 I'm looking into it now.  My hackintosh is running version 2.14.2 and install works fine.

**Comment by rossmartin** [comment]
Thanks for reporting this.  It is fixed via https://github.com/rossmartin/cordova-uglify/commit/03e59f854f5fd909be412a620fe48ca8cb94f24c

**Comment by tetsuo2501** [comment]
I corfirm It works! :)
Thanks a lot!

On Windows 10 x64
Node v 5.2.0
npm v.3.3.12
