### ISSUE TITLE
CSS: minified files with content 'undefined' 

### ISSUE THREAD

**Issue by Diones** [rossmartin/cordova-uglify#17]
I was trying to use cordova-uglify, but my CSS files were receiving the string 'undefined' instead of the css code minified.

I saw your last modification https://github.com/rossmartin/cordova-uglify/commit/03e59f854f5fd909be412a620fe48ca8cb94f24c and you have changed `var CleanCSS    = require('clean-css');` for `var CleanCSS = require(path.join(dependencyPath, 'clean-css'));`

https://github.com/rossmartin/cordova-uglify/blob/master/after_prepare/uglify.js#L12

I don't know why, but replacing `clean-css` inside `node_modules` folder for `clean-css` that I've just installed by `npm` solved my problem. It seems that there is some error with `clean-css` distributed together with cordova-uglify.

**Comment by rossmartin** [comment]
Thanks for reporting I'll have a fix up in a few.

**Comment by Diones** [comment]
Np! :+1:

**Comment by jbavari** [comment]
@rossmartin doesn't mess around, he just crushes it.
