### ISSUE TITLE
Ionic framework error cannot find module uglify-js

### ISSUE THREAD

**Issue by root-io** [rossmartin/cordova-uglify#18]
I got this since you changed `require('uglify-js');` to `require(path.join(dependencyPath, 'uglify-js'));`

```
$ cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.myproject
	Name: Myproject
	Activity: MainActivity
	Android target: android-23
Android project created with cordova-android@5.1.0
Running command: /myproject/hooks/after_prepare/010_add_platform_class.js /myproject
add to body class: platform-android
Running command: /myproject/hooks/after_prepare/uglify.js /myproject
module.js:341
    throw err;
    ^

Error: Cannot find module '/myproject/node_modules/cordova-uglify/node_modules/uglify-js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/myproject/hooks/after_prepare/uglify.js:11:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
Error: Hook failed with error code 1: /myproject/hooks/after_prepare/uglify.js
```

**Comment by rossmartin** [comment]
Thanks for reporting will take a look later tonight when home

**Comment by rossmartin** [comment]
Are you using a Linux distro or OS X?

**Comment by rossmartin** [comment]
First question I have to ask - have you tried removing the hook and the directories in your /myproject/node_modules folder and reinstalling the hook?  I think the error may occur when updating to the latest version of cordova-uglify and dependencies are left over from a previous version.

Can you try this from your /myproject directory - 

`npm uninstall cordova-uglify` (might require sudo)

Then remove all directories in your /myproject/node_modules directory before reinstalling - 

`sudo rm -r node_modules`

Then run this from your /myproject directory -

```npm install cordova-uglify```

I can't replicate the issue on my Macbook currently.  I'd like to find out why this isn't working for you.

**Comment by root-io** [comment]
Hey thanks for your quick answer, I'll try to check this out the next couple days ;)

**Comment by arielfaur** [comment]
I can confirm removing the node_modules folder and then reinstalling cordova-uglify works.

**Comment by root-io** [comment]
Thanks guys, it works, I fixed it with:

```
$ rm -r hooks node_modules
$ rm platforms/* plugins/*
$ cordova platform add android
$ chmod -R 755 hooks
$ build android --release
```

then the output was:

```
Running command: /myproject/hooks/after_prepare/uglify.js /myproject
uglifying js file ...
``
