### ISSUE TITLE
not uglifying

### ISSUE THREAD

**Issue by kingkarki** [rossmartin/cordova-uglify#25]
I installed uglify. And i ran cordova build --release android.
And i decompiled release apk using online tool and found all the javascript and css files are as same as my source code. Nothing is minified. And there is not any error on build as well.

**Comment by nabi-rezvani** [comment]
Same problem here.

**Comment by rossmartin** [comment]
@kingkarki @nabi-rezvani Have you tried setting permissions for your hooks?  

`chmod -R 755 hooks`

What is your config?  Do you see any output from the script?

**Comment by nabi-rezvani** [comment]
I am using Ionic. Tried the plugin that utilizes this one but is customized for Ionic.
https://www.npmjs.com/package/ionic-minify
After installing, changed the settings in hooks folder (not in plugin's folder) and it worked.

**Comment by rossmartin** [comment]
@kingkarki @nabi-rezvani In the latest version I now set all hooks as executable after installing.  You'll no longer need to do a `chmod -R 755 hooks`.

**Comment by kingkarki** [comment]
Thanks it worked to me
