### ISSUE TITLE
How do I tell if this worked?

### ISSUE THREAD

**Issue by sdemurjian** [rossmartin/cordova-uglify#28]
I installed the plugin, ran cordova build android, and nothing seems to indicate that anything was uglified.

**Comment by JeremyColton** [comment]
Same, I am using cordova 3.6.3. I ran the following:
a) from cmd line on my windows machine: npm install cordova-uglify --legacy-bundling
- I saw a lot of 'unmet dependency' lines - see the attached screenshot.  But it didn't say 'failed' at the end of the install.
![uglify](https://cloud.githubusercontent.com/assets/2919478/18322161/ec643c72-7539-11e6-98f6-c80db292692c.JPG)

b) from my Cordova project folder: cordova prepare android --release

I don't see anything extra in my /hooks folder.

What did I miss?

**Comment by JeremyColton** [comment]
You need to run the command inside your root folder of your app as "Administrator" on Windows.

**Comment by rossmartin** [comment]
Sorry I'm late on this.  @JeremyColton chimed in and said he had the same issue on Windows but ran the install as administrator and it worked fine.

@sdemurjian are you using Windows?  Did you have a previous version of cordova-uglify installed and then upgrade?

**Comment by JeremyColton** [comment]
Hi, using the default uglify-config.json :

`{
    "alwaysRun": false,
    "recursiveFolderSearch": true,
    "foldersToProcess": [
        "js",
        "css",
        "img",
        "build"
    ],
    "uglifyJsOptions": {
        "compress": {
            "drop_console": true
        },
        "fromString": true,
        "mangle": true
    },
    "cleanCssOptions": {
        "noAdvanced": true,
        "keepSpecialComments": 0
    },
    "imageminOptions": {
        "jpeg": {
            "progressive": true,
            "arithmetic": false
        },
        "png": {
            "optimizationLevel": 2
        },
        "gif": {
            "interlaced": false
        },
        "svg": {
            "pretty": false
        }
    }
}
`

- nothing happens!  Why is there no compression?

**Comment by rossmartin** [comment]
@JeremyColton 

You can set `alwaysRun` to `true` if you do not want to pass `--release` to a `cordova prepare` or `cordova build` statement to make the hook run.

> If you want to process files only when building/preparing for release include --release in your CLI command like this - cordova prepare ios --release. 

https://github.com/rossmartin/cordova-uglify#usage

If you have the `alwaysRun` set to `false` can you try this and see if the hook runs?
```
cordova prepare ios --release
```

**Comment by JeremyColton** [comment]
Yes, this works :)

I've removed the default "imageminOptions" json and it still minifies images.  How do I stop it from trying to minify images?

**Comment by sdemurjian** [comment]
working as well for me now

**Comment by rossmartin** [comment]
@JeremyColton You can accomplish this by removing the `img` folder from the `foldersToProcess ` option.  However this won't work if you have images nested in your `js` and `css` folders and the `recursiveFolderSearch` is set to `true`.  I might make the image min stuff optional, maybe it isn't so clear.

**Comment by JeremyColton** [comment]
Yes, I have /images under my /css folder.

So instead of excluding the /images folder, can I include it but set the minifying config to effectively zero?

**Comment by rossmartin** [comment]
@JeremyColton Hey I'm just now getting back tonight and won't have time to look into it until tomorrow.  To solve this issue I'll add an option to the `uglify-config.json` to allow turning the image minify off.

**Comment by rossmartin** [comment]
@JeremyColton I'll have a new version out by Sunday with the image minification optional.  I'll let you know when its available.

**Comment by rossmartin** [comment]
@JeremyColton The new version [0.2.5](https://github.com/rossmartin/cordova-uglify/tree/0.2.5) is out and you can now remove the `imageminOptions` in the `uglify-config.json` to disable image compression.
