### ISSUE TITLE
Latest Ionic 2 installation errors and warnings

### ISSUE THREAD

**Issue by MrBokeh** [rossmartin/cordova-uglify#29]
Hi Ross,

This plug-in is not longer working with the latest Ionic 2 during installation, here are the errors that I have got:

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

> gifsicle@3.0.4 postinstall /Users/PROJECT_PATH/node_modules/cordova-uglify/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.1.0 postinstall /Users/PROJECT_PATH/node_modules/cordova-uglify/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.2 postinstall /Users/PROJECT_PATH/node_modules/cordova-uglify/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> cordova-uglify@0.2.5 postinstall /Users/PROJECT_PATH/node_modules/cordova-uglify
> node scripts/install.js

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/Users/PROJECT_PATH/hooks/after_prepare/uglify.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.<anonymous> (/Users/PROJECT_PATH/node_modules/cordova-uglify/scripts/install.js:50:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)

**Comment by rossmartin** [comment]
Hey thanks for letting me know.  I was running it using beta 11 but I'll take a look soon.

**Comment by rossmartin** [comment]
I can confirm this is fixed for me in the latest version (0.2.6).  [Please note that I removed image compression](https://github.com/rossmartin/cordova-uglify#where-did-image-compression-go).

Can you remove your current, try the latest and confirm?  Thanks.

**Comment by rossmartin** [comment]
Also, make sure you install with the `--legacy-bundling` option.

```
npm install cordova-uglify --legacy-bundling
```

**Comment by MrBokeh** [comment]
I still have the same issue, I reckon it's because of the folder permission on the new OS cause the issue, below are the error log and the ionic info:

--------------------------------

> cordova-uglify@0.2.6 postinstall /Users/PROJECT_PATH/node_modules/cordova-uglify
> node scripts/install.js

Updating hooks directory to have execution permissions...
ShellJS: internal error
Error: EPERM: operation not permitted, chmod '/Users/PROJECT_PATH/hooks'
    at Error (native)
    at Object.fs.chmodSync (fs.js:1154:18)
    at innerChmod (/Users/PROJECT_PATH/node_modules/cordova-uglify/node_modules/shelljs/src/chmod.js:210:10)
    at Array.forEach (native)
    at Object._chmod (/Users/PROJECT_PATH/node_modules/cordova-uglify/node_modules/shelljs/src/chmod.js:103:9)
    at Object.chmod (/Users/PROJECT_PATH/node_modules/cordova-uglify/node_modules/shelljs/src/common.js:344:25)
    at Object.<anonymous> (/Users/PROJECT_PATH/node_modules/cordova-uglify/scripts/install.js:56:7)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cordova-uglify" "--legacy-bundling"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! cordova-uglify@0.2.6 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cordova-uglify@0.2.6 postinstall script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cordova-uglify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cordova-uglify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cordova-uglify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/PROJECT_PATH/npm-debug.log

--------------------------------

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan (**Actually this is the latest macOS Sierra 10.12.1**)
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by MrBokeh** [comment]
I have tried to create a blank project, give the entire directory and every single files within sub-directories full permission but still facing the same issue.

**Comment by rossmartin** [comment]
I think it is possible there are permissions issues with your NPM.  Have you ever used `sudo` when doing an `npm install`?  

Here is some info on fixing npm permissions -
https://docs.npmjs.com/getting-started/fixing-npm-permissions

http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo

If it's not an npm issue maybe there is a problem with shelljs and OS X sierra.  I'm still running El Capitan.  I'm away right now but will be able to look more into this tomorrow at the latest.

**Comment by MrBokeh** [comment]
I have tried all of the steps above but the problem still exists (including using brew). I also tried both npm install with and without sudo but with no luck.

**Comment by rossmartin** [comment]
Strange I have no issues with a new Ionic 2 rc1 project.  I'll look into it tomorrow.

**Comment by rossmartin** [comment]
Any chance you can try the latest version (0.2.7) ?  You no longer need the `--legacy-bundling` option.

**Comment by MrBokeh** [comment]
I guess the latest ionic 2 rc3 has uglifyjs built-in as part of the build process but I am not sure it's as good as yours.

**Comment by rossmartin** [comment]
I did notice that the [ionic-app-scripts has been using it for awhile now](https://github.com/driftyco/ionic-app-scripts/blob/master/config/uglifyjs.config.js).  I'm not sure that your apps JS is minified in the main.js file though.  If you wanted to you can configure the uglify js options used in the ionic-app-scripts.  It will be in your projects node_modules directory.

**Comment by rossmartin** [comment]
Please see the info here in the README - https://github.com/rossmartin/cordova-uglify#using-cordova-uglify-with-ionic-2
