### ISSUE TITLE
processFiles err: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by rodrigograca31** [rossmartin/cordova-uglify#41]
If you are having that error because you are using a newer versions of Ionic/Cordova/Android like me where they moved the folder structure change this line:

```js
wwwPath = path.join(platformPath, platform, 'assets', 'www');
```
to
```js
wwwPath = path.join(platformPath, platform, 'app', 'src', 'main', 'assets', 'www');
```

**Comment by rossmartin** [comment]
@rodrigograca31 @simonhaenisch Thanks sorry I haven't gotten to this.  I'm really busy with the day job and trying to buy a house right now, it's a crazy time.

I'll merge your PR @simonhaenisch and get a new version published.
