### ISSUE TITLE
Solved issue with Cordova 7.0.*

### ISSUE THREAD

**Issue by linkito87** [rossmartin/cordova-uglify#43]
Hi!

I discovered an issue with the uglify process on Cordova Android 7.0.*, because the root folder to assets now is in platforms/android/src/main/assets/www

We must to change the line 46 for this:
wwwPath = path.join(platformPath, platform, 'app', 'src', 'main', 'assets', 'www');

Greetings ;)

**Comment by rossmartin** [comment]
Hey thank you for the comment.  I believe this is already fixed as of https://github.com/rossmartin/cordova-uglify/commit/eca730222c0bc9816c3b8f096c985fb999c13135 and is in 0.3.3
