### ISSUE TITLE
Error installing plugin, can't find plugin.xml

### ISSUE THREAD

**Issue by rolinger** [rossmartin/cordova-uglify#45]
Getting this error when trying to install, this is happening on both my PC (for Android) and my MAC.

C:\myapp>cordova plugin add cordova-uglify --save-dev
(node:16892) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Cannot find plugin.xml for plugin "cordova-uglify". Please try adding it again.

Here is my environment:
```
Cordova CLI: 8.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v6.10.3

MAC Envi:
Cordova CLI 7.1.1
```

**Comment by rossmartin** [comment]
Hey this package is a hook, not a Cordova plugin.  Try running

`npm install cordova-uglify --save-dev`

**Comment by rolinger** [comment]
omg....I can't believe I looked right over that.  grrrrrr.....sorry.

**Comment by rolinger** [comment]
ok...it installed.  now I am running `ionic build --release android`, how can I tell if it worked properly.  I am so tired.  :(

**Comment by rolinger** [comment]
everything installed and I am compiling my release build, but I can't tell if `uglify` is doing its thing or not.  As well, something is going wrong, I can do `ionic build android` and it deploys just fine to my device.  but if I do `ionic build android --release` it builds everything just fine, but when I deploy it to my device it says it installed fine but the app, after the splash screen, just goes white screen on me.

When I dive deeper into the release APK, I see my `controllers.js` file is only 9k....yet its supposed to be 160k.  As well, when its compiling the release, I see this line for controllers.js - its like it didn't compress when everything else did.  And when I open that file to view it, it simply says `undefined`.  

Now, I have not compiled this most recent upgraded version of my app for release yet, so I don't know if this is a by-product of `cordova-uglify` or something else related to upgrading cordova and android-cordova.

```
 2569106 assets/www/js/app.js (OK - compressed)
 2571420 assets/www/js/controllers.js (OK)
 2571479 assets/www/js/crc.js (OK - compressed)
 2607835 assets/www/js/directives.js (OK - compressed)
 2608066 assets/www/js/index.js (OK - compressed)
 2622821 assets/www/js/lib/date.format.js (OK - compressed)
 2624183 assets/www/js/services.js (OK - compressed)
```

**Comment by rolinger** [comment]
Crap...and now I can't cleanly uninstall `cordova-uglify` to see if its is the culprit - think I am going to have to rebuild the app from scratch....grrrr.

**Comment by rolinger** [comment]
ok, so it is `cordova-uglify` that is hosing specific files.  The orig files are 174k, 9k and 24k....after it builds the --release, the files are all 9 bytes and simply say `undefined`....when I remove `cordova-uglify` all the files are their proper size and the release apk installs just fine.

**Comment by rolinger** [comment]
I see the other js file undefined issue going on, I am closing this one and moving over there.
