### ISSUE TITLE
Recursively search folder for js files

### ISSUE THREAD

**Issue by mark-veenstra** [rossmartin/cordova-uglify#5]
Why are folders not recursively searched for JS/CSS files? Now we have to identify all subfolders in `www/js/` instead of defining `www/js` in the folders to process.

**Comment by rossmartin** [comment]
Thank you for pointing this out.  I've considered it before but would like to make it optional.  I'll add and enable it by default with the ability to disable and manually indicate directories to minify.

**Comment by rossmartin** [comment]
I added support in [this commit (faffc7e)](https://github.com/rossmartin/cordova-uglify/commit/faffc7e08377f0db8326fac1e0fe946744c799d0)

Thanks!

**Comment by mark-veenstra** [comment]
Thnx for the quick solve, Just tested and confirmed working perfectly
