### ISSUE TITLE
Support ES6

### ISSUE THREAD

**Issue by jfoclpf** [rossmartin/cordova-uglify#51]
This package could also support ES6, for that you just need to change from `uglify-js` to `uglify-es`
They have the same syntax, so, you just need to change your `package.json`

**Comment by rossmartin** [comment]
Thank you for your comment here and the other issue. `uglify-es` has been abandoned. This hook did use it for a brief time  before moving back to `uglify-js`.

**Comment by jfoclpf** [comment]
Where do you see that `uglify-es` has been abandoned?
There is no reference for that on the npm page: https://www.npmjs.com/package/uglify-es

I'm asking because I use it for my projects

Just last week it got 1,3 million downloads, it really does not seem abandoned

![image](https://user-images.githubusercontent.com/3984909/94125094-34851180-fe56-11ea-99ea-b6c63e1a33bd.png)

**Comment by jfoclpf** [comment]
Ah, ok, I saw now. For ES6 compatibility you can use [`terser`](https://www.npmjs.com/package/terser)

If Cordova build supports ES6, it's a pity that your module does not support ES6

> uglify-es has been forked and the new project is called terser. For projects that need ES6 support, use it instead of uglify-es, since all new development will be happening over there (and things like webpack are switching over to it shortly too):
https://github.com/fabiosantoscode/terser
